# RunPod Project Configuration
name = "test"

[project]
uuid = "9a4c68be"
base_image = "runpod/base:0.6.1-cuda11.8.0"
gpu_types = [
    "NVIDIA GeForce RTX 4080",  # 16GB
    "NVIDIA RTX A4000",         # 16GB
    "NVIDIA RTX A4500",         # 20GB
    "NVIDIA RTX A5000",         # 24GB
    "NVIDIA GeForce RTX 3090",  # 24GB
    "NVIDIA GeForce RTX 4090",  # 24GB
    "NVIDIA RTX A6000",         # 48GB
    "NVIDIA A100 80GB PCIe",    # 80GB
]
gpu_count = 1
volume_mount_path = "/runpod-volume"
# 4040はファイルブラウザ機能なので削る
#ports = "4040/http, 7270/http, 22/tcp"
ports = "7270/http, 22/tcp"
container_disk_size_gb = 100

[project.env_vars]
POD_INACTIVITY_TIMEOUT = "1800"
RUNPOD_DEBUG_LEVEL = "debug"
UVICORN_LOG_LEVEL = "warning"
TMPDIR = "/runpod-volume/tmp"

[endpoint]
active_workers = 0
max_workers = 2
flashboot = true

[runtime]
python_version = "3.10"
handler_path = "src/handler.py"
requirements_path = "builder/requirements.txt"
